spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/hqwmall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            username: niehaibo
            password: niehaibo


mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.nhb.springcloud.entities #所有entity别名类所在包



