server:
  port: 8004


spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hqwmall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: niehaibo
    password: niehaibo
    driver-class-name: com.mysql.jdbc.Driver #驱动
  #服务名
  application:
    name: hqwmall_product
  #注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.36:8848

#mybatis配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      







