server:
  port: 8001

#spring:
#  activemq:
#    broker-url: tcp://192.168.174.12:61616
#    user: admin
#    password: admin
#  jms:
#    pub-sub-domain: false # false = queue  true = topic

#自己队列名字
#myqueue: boot-activemq-queue
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hqwmall_oms?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: dev
    password: Dev123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 10.86.11.16:8848





#mybatis-plus:
#  mapper-locations: classpath:mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto