server:
  port: 8001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hqwmall_sms??useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: niehaibo
    password: niehaibo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.12:8848
  application:
    name: hqwmall-coupon




mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto